# Admixture Visualization Pipeline Configuration
# This file overrides CLI arguments and .env defaults

# Input options (single or batch mode)
q_file: null  # Path to single Q file, or null for batch
input_dir: inst/extdata/Pdepint  # Will be resolved to extdata/Pdepint by system.file()
log_dir: null    # Will be resolved to extdata/Pdepint by system.file()

# Data files (will be resolved by system.file() if null)
fam: null        # Will be resolved to extdata/Pdepint/Pdepint_M095_noSele.fam
popmap: null     # Will be resolved to extdata/Pdepint/Pops_Pdepint.csv
coords: null     # Will be resolved to extdata/Pdepint/Pdepint_Lat_Long_Coords.csv

# Output and processing
output_dir: inst/extdata/Pdepint/plot_results  # Output will be resolved to installed extdata location
k_value: null  # Process specific K, or null for all K > 1
labels: true # For population labels
parallel_workers: 4
dpi: 300

# Spatial options (optional)
bbox: null  # Custom bbox as [xmin, ymin, xmax, ymax], or null for auto
padding: 0.15  # Padding for auto bbox (0.0 to 1.0)
cache_dir: cache_maps  # Custom cache directory, or null for default (package library)

# Example usage: Rscript R/admixture_visualization.R --conf_file config/config.yaml
